# Generated by Django 4.1.6 on 2023-05-03 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0003_dweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dweet',
            old_name='user',
            new_name='email',
        ),
    ]
